syntax = "proto3";

package api.data_tunnel.v1;

option go_package = "github.com/alert666/alertmanager-proto/gen/go/data_tunnel/v1";

service TunnelService {
  rpc DataTunnel(stream TunnelMessage) returns (stream TunnelMessage);
}

message TunnelMessage {
   string TaskId = 1;
  oneof Payload {
    // Client → Server
    Init          Init           = 10;
    CommandResult CommandResult = 11;

    // Server → Client
    Command Command = 20;
  }
}

// Client → Server: 客户端连上后发送的注册信息
message Init {
  string AgentId   = 1;
  string ClusterId = 2;
  string Version    = 3;
  map<string, string> Labels = 4;
}

// Client → Server: 命令执行结果
message CommandResult {
  CommandType CommandType = 1;
  bool        Ok           = 2;
  string      Error        = 3;
  bytes       Data         = 4;
}

// Server → Client: 服务端下发给客户端的指令
message Command {
  CommandType        Type        = 1;
  string             Description = 2;
  map<string, string> Params     = 3;
}

enum CommandType {
  COMMAND_TYPE_UNSPECIFIED                    = 0;
  COMMAND_TYPE_GET_ALERTMANAGER_CONFIG        = 1;
  COMMAND_TYPE_GET_PROMETHEUS_CONFIG          = 2;
  COMMAND_TYPE_RELOAD_ALERTMANAGER            = 3;
  COMMAND_TYPE_RELOAD_PROMETHEUS              = 4;
  COMMAND_TYPE_UPDATE_ALERTMANAGER_CONFIG     = 5;
  COMMAND_TYPE_UPDATE_PROMETHEUS_CONFIG       = 6;
}
